import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import sys
import numpy as np


def calculate_zeta(error_data: pd.Series, setpoint: float = 0) -> dict:
    """
    Calculate damping ratio (zeta) and related metrics from error data.

    Args:
        error_data: Pandas Series of error values
        setpoint: The target setpoint

    Returns:
        Dictionary with zeta and related metrics
    """
    # Find steady-state error (final value)
    steady_state = error_data.iloc[-1]

    # Find overshoot: maximum deviation from setpoint
    overshoot_value = abs(error_data.min() - setpoint) if (setpoint + error_data.min()) < setpoint else abs(
        error_data.max() - setpoint)

    # Calculate overshoot percentage relative to initial error
    initial_error = abs(error_data.iloc[0] - setpoint)
    if initial_error > 0:
        overshoot_percent = (overshoot_value / initial_error) * 100
    else:
        overshoot_percent = 0

    # Calculate zeta from overshoot using inverse formula
    # Overshoot% = e^(-ζπ / √(1-ζ²)) × 100
    # Derived: ζ = -ln(OS/100) / √(π² + ln²(OS/100))
    if 0 < overshoot_percent < 100:
        ln_os = np.log(overshoot_percent / 100)
        zeta = -ln_os / np.sqrt(np.pi ** 2 + ln_os ** 2)
    elif overshoot_percent >= 100:
        zeta = 0  # Unstable
    else:
        zeta = 1.0  # No overshoot = critically damped or overdamped

    # Count oscillations (peaks and troughs)
    oscillations = count_oscillations(error_data)

    return {
        'zeta': zeta,
        'overshoot_percent': overshoot_percent,
        'steady_state_error': steady_state,
        'oscillations': oscillations,
    }


def count_oscillations(data: pd.Series) -> int:
    """Count number of oscillations in the data"""
    if len(data) < 3:
        return 0

    crosses = 0
    for i in range(1, len(data) - 1):
        # Check if sign changes (crosses zero)
        if (data.iloc[i - 1] - data.iloc[i]) * (data.iloc[i] - data.iloc[i + 1]) < 0:
            crosses += 1

    return crosses // 2


def analyze_pid_log(csv_file: str, setpoint: float = 0) -> None:
    """
    Analyze PID log CSV file and display error over time graph.

    Args:
        csv_file: Path to the CSV file generated by PidCalc
        setpoint: The target setpoint (default 0)
    """
    try:
        # Read CSV file
        df = pd.read_csv(csv_file)

        # Convert timestamp to datetime
        df['Timestamp'] = pd.to_datetime(df['Timestamp'])

        # Calculate relative time (seconds from start)
        start_time = df['Timestamp'].iloc[0]
        df['RelativeTime'] = (df['Timestamp'] - start_time).dt.total_seconds()

        # Calculate zeta and metrics
        metrics = calculate_zeta(df['Error'], setpoint)

        # Create figure and axis
        fig, ax = plt.subplots(figsize=(12, 6))

        # Plot error over time
        ax.plot(df['RelativeTime'], df['Error'], label='Error', linewidth=2, marker='o', markersize=3)

        # Add setpoint as dotted line
        ax.axhline(y=setpoint, color='r', linestyle='--', linewidth=2, label=f'Setpoint ({setpoint})')

        # Add zero line (reference)
        if setpoint != 0:
            ax.axhline(y=0, color='gray', linestyle=':', linewidth=1, alpha=0.5, label='Zero')

        # Labels and title
        ax.set_xlabel('Time (seconds)', fontsize=12)
        ax.set_ylabel('Error', fontsize=12)
        ax.set_title(f'PID Error Over Time (ζ = {metrics["zeta"]:.3f})', fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=10)

        # Tight layout
        plt.tight_layout()

        # Display statistics
        print(f"\n{'=' * 60}")
        print(f"PID Analysis: {csv_file}")
        print(f"{'=' * 60}")
        print(f"Total samples: {len(df)}")
        print(f"Duration: {df['RelativeTime'].iloc[-1]:.2f} seconds")

        print(f"\n{'DAMPING RATIO (ZETA)':^60}")
        print(f"{'-' * 60}")
        print(f"  Zeta (ζ): {metrics['zeta']:.4f}")
        if metrics['zeta'] < 0.7:
            damping_type = "Underdamped (Oscillatory)"
        elif metrics['zeta'] < 1.0:
            damping_type = "Lightly Underdamped"
        elif metrics['zeta'] == 1.0:
            damping_type = "Critically Damped (Ideal)"
        elif metrics['zeta'] < 1.5:
            damping_type = "Lightly Overdamped"
        else:
            damping_type = "Overdamped (Slow)"
        print(f"  Classification: {damping_type}")
        print(f"  Overshoot: {metrics['overshoot_percent']:.2f}%")
        print(f"  Oscillations: {metrics['oscillations']}")

        print(f"\nError Statistics:")
        print(f"  Min Error: {df['Error'].min():.4f}")
        print(f"  Max Error: {df['Error'].max():.4f}")
        print(f"  Mean Error: {df['Error'].mean():.4f}")
        print(f"  Std Dev: {df['Error'].std():.4f}")
        print(f"  Steady-State Error: {metrics['steady_state_error']:.4f}")

        print(f"\nIntegral Statistics:")
        print(f"  Max Integral: {df['Integral'].max():.4f}")
        print(f"  Min Integral: {df['Integral'].min():.4f}")

        print(f"\nDerivative Statistics:")
        print(f"  Max Derivative: {df['Derivative'].max():.4f}")
        print(f"  Min Derivative: {df['Derivative'].min():.4f}")

        print(f"\nOutput Statistics:")
        print(f"  Max Output: {df['Out'].max():.4f}")
        print(f"  Min Output: {df['Out'].min():.4f}")
        print(f"{'=' * 60}\n")

        # Show plot
        plt.show()

    except FileNotFoundError:
        print(f"Error: File '{csv_file}' not found!")
        sys.exit(1)
    except Exception as e:
        print(f"Error analyzing file: {e}")
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python logAnalysis.py <csv_file> [setpoint]")
        print("Example: python logAnalysis.py pid_logs/pidY.csv 0")
        sys.exit(1)

    csv_file = sys.argv[1]
    setpoint = float(sys.argv[2]) if len(sys.argv) > 2 else 0

    analyze_pid_log(csv_file, setpoint)